In [145]:
import numpy as np
import pandas as pd
import datetime

import dataset
import trainer
import models

from sklearn.model_selection import train_test_split

%load_ext autoreload
%autoreload 2

seed = 0
'''
np.random.seed(seed)
import torch
torch.manual_seed(seed)
if trainer.opt['cuda']:
    torch.cuda.manual_seed_all(seed)
'''

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


"\nnp.random.seed(seed)\nimport torch\ntorch.manual_seed(seed)\nif trainer.opt['cuda']:\n    torch.cuda.manual_seed_all(seed)\n"

In [134]:
df = pd.read_csv(r'C:\Users\mirce\OneDrive\Code\UiPath\Classification\ocr_label.csv')
df = df.rename(columns = {'Text':'text', 'Label':'label'})
df = df[df.label != 'Serve on Panel']
df = df[df.label != 'Legal']
df

text                    label
0       URITED ETHTES  Mr, Kenneth C. Frazier Chai...                   Awards
1   By way of background, CSFP is a simple and dir...                   Awards
2   Kenneth C. Frazier Merck Chairman, President &...                   Awards
3      s VAR 0 5 2018  March 1, 2018  Kenneth C. F...                   Awards
4   Merck  Sai The Chief Executive Officer gn 1550...                   Awards
5   MICHAEL R. BLOOMBERG  March 9, 2018  Mr, Kenne...          Decline Routine
6   A  Fendelander, Helene Chrobalk  From: Fendela...          Decline Routine
7   DeRose, Annette M  From: Frazier, Kenneth C.  ...          Decline Routine
8   Fendelander, Helene Chrobak  From: Fendelander...          Decline Routine
9   Frazier, Kenneth C.  From: Frazier, Kenneth C,...          Decline Routine
10  Fendelander, Helene Chrobak  From: DeRose, Ann...          Decline Routine
11  to see two global luminaries share the stage f...          Decline Routine
12  am not an expert in “search” and was a bit ske...                       HR
13  Thank you for re-sending your email {your earl...                       HR
14  Perez, Lisa       From: Dilley, Karen A.  Sent...                       HR
15  Fendelander, Helene Chrobak     From: Shah, Sh...         Keynote Speaking
16  Jt would be an honor to have the opportunity t...         Keynote Speaking
17  Perez, Lisa Ee 3 SS Sms  From: Perez, Lisa  Se...         Keynote Speaking
18  Kenneth C. Frazier Moerclc Chairman, President...         Keynote Speaking
19  Fendelander, Helene Chrobak  Fron: Fendelander...         Keynote Speaking
20  All the best, have a nice week end, best regar...         Keynote Speaking
21  t am including some information on the IESE GA...         Keynote Speaking
22         EERE WE SRAEMA DS FE LA TECH PLS CUBA E...         Keynote Speaking
23  MAR 0 9 2018  & Penn Medicine KENNETH C. FRAZI...         Keynote Speaking
24  Fendelander, Helene Chrobalc  From: Loxam, Ter...         Keynote Speaking
25  Kenneth C. Frazier Merck Chairman, President &...         Keynote Speaking
26  MAR 26 2018 KENNETH C. FRAZIER     45 East Cit...         Keynote Speaking
27  { an  . | od Nor FH A  4FIESE  University of N...         Keynote Speaking
28  Perez, Lisa Ee 3 SS Sms  From: Perez, Lisa  Se...         Keynote Speaking
29     45 East City Ave #300 Bala Cynwyd, PA 19004...         Keynote Speaking
30  #  Perez, Lisa  EE AOA ee R24 CERCA RECESS,  F...         Keynote Speaking
32  Fendelander, Helene Chrobak  From: DeRose, Ann...            Media Decline
33  From: darryl@mediamoxye.com [maiito:  Sent: Fr...            Media Decline
34  pd Acgy  DeRose, Annette M  From: DeRose, Anne...            Media Decline
35  From: Ron Davis [mailto ron@insightssuccess.co...            Media Decline
36  WAR 12 21g Kaine, FRAZIER  11/18/2017  Kenneth...  National Service Center
37  Ken Frazier, CEO One Merck Drive  P.O. Box 100...  National Service Center
38  Merck National Service Center NU} 01 October 3...  National Service Center
39  OD  np ———————  ee a et a ot ft  Of most conce...  National Service Center
40  430% 2018  KENNETH C FRAZIER  vierck Nationa S...  National Service Center
41  0CT 812017 INS CO Gctober 24, 2017 i S 7 2 KEN...  National Service Center
42     , “ FRAZpey,  XE, Merck National S 15 Novem...  National Service Center
43  Merck & Co Inc Cd 2000 Galloping Hill Road  Ke...  National Service Center
44  ¢ ae i i WAS  nEB 37 201g  Cone! C KENNER 2   ...  National Service Center
45  Fendelander, Helene Chrobak  From: Fendelander...          Passing on Info
46  Jay T. Leverett  Jay T. Leverett is a cattle r...          Passing on Info
47  Fendelander, Helene Chrobak  From: Fendelander...          Passing on Info
48      1 Commerce Drive; Suite 310 Cranford, NJ 0...          Passing on Info
49  MAR 122018  KENNY - March 5, 2018 ETH C. FRAZI...          Passing on Info
52  with their families - shown to reduce recidivi...          Willing to meet
53  NEW JERSEY OPINI

In [146]:
np.random.seed(seed)
df_train, df_test = train_test_split(df, test_size=0.25, stratify=df.label)

In [147]:
df_train

text                    label
19  Fendelander, Helene Chrobak  Fron: Fendelander...         Keynote Speaking
18  Kenneth C. Frazier Moerclc Chairman, President...         Keynote Speaking
41  0CT 812017 INS CO Gctober 24, 2017 i S 7 2 KEN...  National Service Center
47  Fendelander, Helene Chrobak  From: Fendelander...          Passing on Info
34  pd Acgy  DeRose, Annette M  From: DeRose, Anne...            Media Decline
24  Fendelander, Helene Chrobalc  From: Loxam, Ter...         Keynote Speaking
27  { an  . | od Nor FH A  4FIESE  University of N...         Keynote Speaking
46  Jay T. Leverett  Jay T. Leverett is a cattle r...          Passing on Info
28  Perez, Lisa Ee 3 SS Sms  From: Perez, Lisa  Se...         Keynote Speaking
54  Kenneth C. Frazier Merck Chairman, President &...          Willing to meet
1   By way of background, CSFP is a simple and dir...                   Awards
45  Fendelander, Helene Chrobak  From: Fendelander...          Passing on Info
35  From: Ron Davis [mailto ron@insightssuccess.co...            Media Decline
43  Merck & Co Inc Cd 2000 Galloping Hill Road  Ke...  National Service Center
3      s VAR 0 5 2018  March 1, 2018  Kenneth C. F...                   Awards
15  Fendelander, Helene Chrobak     From: Shah, Sh...         Keynote Speaking
42     , “ FRAZpey,  XE, Merck National S 15 Novem...  National Service Center
8   Fendelander, Helene Chrobak  From: Fendelander...          Decline Routine
20  All the best, have a nice week end, best regar...         Keynote Speaking
2   Kenneth C. Frazier Merck Chairman, President &...                   Awards
52  with their families - shown to reduce recidivi...          Willing to meet
13  Thank you for re-sending your email {your earl...                       HR
37  Ken Frazier, CEO One Merck Drive  P.O. Box 100...  National Service Center
26  MAR 26 2018 KENNETH C. FRAZIER     45 East Cit...         Keynote Speaking
30  #  Perez, Lisa  EE AOA ee R24 CERCA RECESS,  F...         Keynote Speaking
29     45 East City Ave #300 Bala Cynwyd, PA 19004...         Keynote Speaking
9   Frazier, Kenneth C.  From: Frazier, Kenneth C,...          Decline Routine
11  to see two global luminaries share the stage f...          Decline Routine
5   MICHAEL R. BLOOMBERG  March 9, 2018  Mr, Kenne...          Decline Routine
23  MAR 0 9 2018  & Penn Medicine KENNETH C. FRAZI...         Keynote Speaking
6   A  Fendelander, Helene Chrobalk  From: Fendela...          Decline Routine
55  COMMUNITY FOUNDATION  March 12, 2018  Mr. Ken ...          Willing to meet
4   Merck  Sai The Chief Executive Officer gn 1550...                   Awards
40  430% 2018  KENNETH C FRAZIER  vierck Nationa S...  National Service Center
17  Perez, Lisa Ee 3 SS Sms  From: Perez, Lisa  Se...         Keynote Speaking
32  Fendelander, Helene Chrobak  From: DeRose, Ann...            Media Decline
14  Perez, Lisa       From: Dilley, Karen A.  Sent...                       HR
44  ¢ ae i i WAS  nEB 37 201g  Cone! C KENNER 2   ...  National Service Center
49  MAR 122018  KENNY - March 5, 2018 ETH C. FRAZI...          Passing on Info

In [148]:
df_test.sort_values(by='label')

text                    label
0       URITED ETHTES  Mr, Kenneth C. Frazier Chai...                   Awards
7   DeRose, Annette M  From: Frazier, Kenneth C.  ...          Decline Routine
10  Fendelander, Helene Chrobak  From: DeRose, Ann...          Decline Routine
12  am not an expert in “search” and was a bit ske...                       HR
25  Kenneth C. Frazier Merck Chairman, President &...         Keynote Speaking
21  t am including some information on the IESE GA...         Keynote Speaking
16  Jt would be an honor to have the opportunity t...         Keynote Speaking
22         EERE WE SRAEMA DS FE LA TECH PLS CUBA E...         Keynote Speaking
33  From: darryl@mediamoxye.com [maiito:  Sent: Fr...            Media Decline
36  WAR 12 21g Kaine, FRAZIER  11/18/2017  Kenneth...  National Service Center
39  OD  np ———————  ee a et a ot ft  Of most conce...  National Service Center
38  Merck National Service Center NU} 01 October 3...  National Service Center
48      1 Commerce Drive; Suite 310 Cranford, NJ 0...          Passing on Info
53  NEW JERSEY OPINION  Kudos to Christie for clos...          Willing to meet

In [149]:
data = dataset.Dataset(None, df_train, df_test)

dataset.opt['text_pp_remove_stop_words'] = False
trainer.opt['bow_ngram_range'] = (1, 3)
trainer.opt['bow_min_df'] = 3
mytrainer = trainer.BOWTrainer(data)
mytrainer.train()

2018-06-03 14:48:32.920770 Building vocabulary
2018-06-03 14:48:32.924757 Preparing data
2018-06-03 14:48:32.934730 Vectorizing
2018-06-03 14:48:32.981597 Traing
2018-06-03 14:48:32.986561 (0.8461538461538461, 0.42857142857142855)


In [139]:
data.le.classes_

array(['Awards', 'Decline Routine', 'HR', 'Keynote Speaking',
       'Media Decline', 'National Service Center', 'Passing on Info',
       'Willing to meet'], dtype=object)

In [150]:
mytrainer.eval()

2018-06-03 14:48:52.029548 Vectorizing
2018-06-03 14:48:52.037660 0.42857142857142855
[[0 0 0 1 0 0 0 0]
 [0 0 0 2 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 2 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]]


In [152]:
mytrainer = trainer.NNTrainer(data, num_classes=8)

2018-06-03 14:50:06.440049 Loading Glove
2018-06-03 14:50:07.810425 Building vocabulary
2018-06-03 14:50:07.830379 Preparing data
2018-06-03 14:50:07.834340 Buidling embeddings
2018-06-03 14:50:09.226773 Creating model


In [129]:
sorted(mytrainer.dataset.char2ids)

[' ',
 '!',
 '"',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '=',
 '?',
 '@',
 '[',
 ']',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '{',
 '|',
 '}',
 '~',
 '—',
 '’',
 '“',
 '”']

In [122]:
mytrainer.reset()

2018-06-02 12:58:02.712731 Creating model


In [153]:
mytrainer.test()

C:\Users\mirce\git\ML\Experiments\TextClassification\models.py:246: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(X)


2.0778344 0.15384615384615385
0.15384615384615385


In [155]:
mytrainer.train(epochs=49000, epochs_eval=1000, verbose=False)

2018-06-03 14:50:50.730296 Training


C:\Users\mirce\git\ML\Experiments\TextClassification\models.py:246: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(X)


epoch 001000 loss 1.8000 train acc 0.4615 test acc 0.3571
epoch 002000 loss 1.6573 train acc 0.6923 test acc 0.5714
epoch 003000 loss 1.4925 train acc 0.7949 test acc 0.6429
epoch 004000 loss 1.4733 train acc 0.7949 test acc 0.6429
epoch 005000 loss 1.3787 train acc 0.9487 test acc 0.5000
epoch 006000 loss 1.3382 train acc 0.9487 test acc 0.5714
epoch 007000 loss 1.3304 train acc 0.9487 test acc 0.5714
epoch 008000 loss 1.3261 train acc 0.9487 test acc 0.6429
epoch 009000 loss 1.2883 train acc 1.0000 test acc 0.5000
epoch 010000 loss 1.2815 train acc 1.0000 test acc 0.6429
epoch 011000 loss 1.2789 train acc 1.0000 test acc 0.6429
epoch 012000 loss 1.2776 train acc 1.0000 test acc 0.6429
epoch 013000 loss 1.2768 train acc 1.0000 test acc 0.6429
epoch 014000 loss 1.2763 train acc 1.0000 test acc 0.6429
epoch 015000 loss 1.2760 train acc 1.0000 test acc 0.6429
epoch 016000 loss 1.2757 train acc 1.0000 test acc 0.5714
epoch 017000 loss 1.2755 train acc 1.0000 test acc 0.5714
epoch 018000 l

In [156]:
mytrainer.eval()

C:\Users\mirce\git\ML\Experiments\TextClassification\models.py:246: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(X)


2018-06-03 15:05:23.272665 0.7857142857142857
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [1 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [93]:
np.concatenate((np.array([]), np.array([1,2])))

array([1., 2.])