In [47]:
import numpy as np
import pandas as pd
import datetime

import dataset
import trainer

from sklearn.model_selection import train_test_split

%load_ext autoreload
%autoreload 2

seed = 0
np.random.seed(seed)
'''import torch
torch.manual_seed(seed)
if trainer.opt['cuda']:
    torch.cuda.manual_seed_all(seed)
'''

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


"import torch\ntorch.manual_seed(seed)\nif trainer.opt['cuda']:\n    torch.cuda.manual_seed_all(seed)\n"

In [72]:
folder = r'C:\Users\mirce\OneDrive\Code\UiPath\Invoice'
preprocess = False
save = True
if preprocess:
    df = pd.read_csv(folder + r'\dataset-synthetic.tsv', sep='\t')
    df = df.rename(columns = {'value':'text'})
    train = int(df.shape[0]*0.8)
    df_train = pd.DataFrame(df[:train])
    df_test = pd.DataFrame(df[train:])
    data = dataset.Dataset(None, df_train, df_test)
    data.preprocess()
    if save:
        data.df_train['words'] = data.df_train['words'].apply(lambda x: ' '.join(x))
        data.df_test['words'] = data.df_test['words'].apply(lambda x: ' '.join(x))
        data.df_train.to_csv(folder + r'\train.csv', index=False)
        data.df_test.to_csv(folder + r'\test.csv', index=False)        
        df_train['words'] = df_train['words'].apply(lambda x: x.split(' '))
        df_test['words'] = df_test['words'].apply(lambda x: x.split(' '))
else:
    df_train = pd.read_csv(folder + r'\train.csv')
    df_train = df_train.fillna(' ')
    df_train['words'] = df_train['words'].apply(lambda x: x.split(' '))
    df_test = pd.read_csv(folder + r'\test.csv')
    df_test = df_test.fillna(' ')
    df_test['words'] = df_test['words'].apply(lambda x: x.split(' '))
    data = dataset.Dataset(None, df_train, df_test)
    


In [53]:
file = r'C:\Users\mirce\OneDrive\Datasets\Classification\Receipts\dataset.csv'
df = pd.read_csv(file)
#df = df[['text', 'label', 'x1', 'y1', 'x2', 'y2']]
df = df[['text', 'label']]
df = df[df.label != 'O']
df = df[df.label != 'I']
np.random.seed(seed)
df_train, df_test = train_test_split(df, test_size=0.25, stratify=df.label)
data = dataset.Dataset(None, df_train, df_test)
data.df_train

text  label  \
670              HYATT REGENCY CAMBRIDGE      2   
231             Charlotte, NC 28277-3654      0   
229                           Ballantyne      0   
46                   535 Bellevue Square      0   
643           CHECK # 66608 DATE 4/02/18      1   
355                    05/21/18 12:48:21      1   
674                     APR03'18 10:08AM      1   
9                           Total $16.00      3   
153                            Mix Longe      2   
985           The Westin NY Times Square      0   
512                        FairField Inn      2   
17                     Amount: 16.00 USD      3   
448                Cardinal Health South      2   
35                  Date: 05/21/18 15:30      1   
342                    RUBENS CUBAN CAF�      2   
255                      TOTAL i: $13.00      3   
906                             Sakagura      2   
430                         Panera Bread      2   
557                             300 EAST      2   
205                              AMOUNT:      3   
509                         Total: 48.48      3   
109          High Flying Foods SFO, LLC.      2   
176               05/22/2018 1:39PM 0001      1   
196                        Intl. Airport      0   
32                          Total $20.00      3   
560                  Charlotte, NC 28203      0   
161                    5/22/2018 7:31 AM      1   
431                            Cafe 3339      0   
0                The Ballavue Collection      2   
274                        TOTAL : $5.50      3   
..                                   ...    ...   
394                   Temple Tarrace, FL      0   
450                     Dublin, OH 43017      0   
889                          Black Sushi      2   
286  5/16/2018 Deschis: 7:14 Inchis 9:00      1   
896          Date : 4/5/2018 12:55:42 PM      1   
760                         Total: 78.48      3   
276                        AMOUNT : $5.5      3   
84                  Burlingame, CA 94010      0   
47                    Bellevue, WA 98004      0   
582                    6518 Fairview Rd.      0   
696              Hyatt Regency Cambridge      2   
1                        Bellevue, 98004      0   
164                         Total: 5. 00      3   
230                  13855 Conlan Circle      0   
479                 Trans Date: 5/9/2018      1   
485                        TOTAL : 25.77      3   
195                           Pittsburgh      0   
869                         New York, NY      0   
453                   8 MAY' 18 11:47 AM      1   
155                          66 Hale Ave      0   
162                      Total Due $0.00      3   
961                           ROMULUS M1      0   
174                    360 HAMILTON AVE.      0   
742                         TOTAL: 20.12      3   
987                   New York, NY 10036      0   
240                  13855 Conlan Circle      0   
802                     Phillips Seafood      2   
940                     AMOUNT PAID 5.98      3   
919                       Total: $ 35.99      3   
326                               #NAME?      3   

                             text_parsed  \
670              HYATT REGENCY CAMBRIDGE   
231             Charlotte, NC 28277-3654   
229                           Ballantyne   
46                   535 Bellevue Square   
643           CHECK # 66608 DATE 4/02/18   
355                    05/21/18 12:48:21   
674                     APR03'18 10:08AM   
9                           Total $16.00   
153                            Mix Longe   
985           The Westin NY Times Square   
512                        FairField Inn   
17                     Amount: 16.00 USD   
448                Cardinal Health South   
35                  Date: 05/21/18 15:30   
342                    RUBENS CUBAN CAF�   
255                      TOTAL i: $13.00   
906                             Sakagura   
430                         Panera Bread   
557                             300 E

In [34]:
df_test.sort_values(by='label')

text label
668                   472 SHAWMUT AVE     A
129              Burlingame, CA 94010     A
212                     Intl, Airport     A
532                  1085 Morrison Dr     A
494                  Dublin, OH 43017     A
962                             48174     A
285              Nr #277942 Masa  #44     A
493                   6360 Frantz Rd.     A
635                  Irving, TX 75063     A
241          Charlotte, NC 28277-3654     A
583               Chariotte, NC 28210     A
960                 29240 ECORSE ROAD     A
23                    Bellevue, 98004     A
239                        Ballantyne     A
469            COLUMBUS INT'L AIRPORT     A
907                211 East 43rd B 1F     A
156            White Plains, NY 10601     A
824                NEW YORK, NY 10018     A
776                  Apr03’18 06:43PM     D
338             to: 05/22/18 17:03:50     D
131            Date: May15'18 08:28PM     D
871  POS:02-02670107 04/01/2018 20:27     D
913             Date: 4/4/18, 7:10 PM     D
70                  15 May'18 8:10 AM     D
238      Back May 22, 2018 at 3:56 PM     D
218                       85/16/13 23     D
964               DATE 02/01/18 10:48     D
250                  05/12/2018 17:21     D
216                    05/14/18 16:44     D
639                    Date: 05/02/18     D
94             Trans Date : 5/15/2018     D
581               Harper's Restaurant     N
312           MATT THE MILLERS TAVERN     N
393                 Fuzzy's Taco Shop     N
468                LAND GRANT BREW CO     N
492        Hyde Park Prime Steakhouse     N
64              COURTYARD BY MARRIOTT     N
853                      Bibble & Sip     N
22            The Bellevue Collection     N
530                     Butcher & Bee     N
284                           Prenota     N
695                            Zephyr     N
235                 Order Total $2.11     T
42                  Amount: 20.00 USD     T
876                       Total 12.15     T
837                   Total: $ 124.10     T
59                       Total: 74.70     T
339             Amount to pay: $20.00     T
462                    Payment $11.84     T
189                    TO0TAL $28. 77     T
545                           Err:509     T
304                Total Brut: 358.00     T
221                           AMOUNT:     T
206                           $48. 00     T
865                      Total $22.21     T

In [35]:
data.le.classes_

array(['A', 'D', 'N', 'T'], dtype=object)

In [37]:
data.le.inverse_transform([0,1,2,3])

c:\python36\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array(['A', 'D', 'N', 'T'], dtype=object)

In [55]:
data.prepare_wordlevel(trainer.opt)

2018-06-04 19:22:56.108938 Loading Glove
2018-06-04 19:22:57.472264 Building vocabulary
2018-06-04 19:22:57.474259 Preparing data
2018-06-04 19:22:57.490218 Buidling embeddings


In [56]:
data.vocabulary['words_ignored']

{'28277': 1,
 '3654': 1,
 '66608': 1,
 '4/02/18': 1,
 '05/21/18': 4,
 '12:48:21': 1,
 "apr03'18": 1,
 '10:08am': 1,
 '�': 1,
 'sakagura': 1,
 '05/22/2018': 2,
 '1:39pm': 1,
 '28203': 1,
 '5/22/2018': 2,
 '3339': 1,
 'ballavue': 1,
 '3418': 1,
 'apr05’18': 1,
 '3:54pm': 1,
 '6725': 1,
 '4941': 1,
 '04/03/18': 1,
 'islandmart': 1,
 '94080': 1,
 '08:01:00': 1,
 '33612': 2,
 'bucshblv': 1,
 '04/03/2018': 1,
 '05/12/18': 1,
 '3-apr-2018': 1,
 '3/27/1b': 1,
 '04/04/2018': 1,
 'resteraunt': 1,
 '2456': 1,
 'apr03’18': 1,
 '20:04': 1,
 '33617': 1,
 '12:49pm': 1,
 '3,0846.00014': 1,
 '04/09/2018': 1,
 'b701': 1,
 '04/04/18': 2,
 '07:35': 1,
 '552.40': 1,
 '09:22pm': 1,
 '447.48': 1,
 'frni': 1,
 '05/23/18': 1,
 '00:13': 1,
 "may07'18": 1,
 '07:56pm': 1,
 '29403': 1,
 '0608': 1,
 '193.04': 1,
 '224.16': 1,
 'hakkasan': 1,
 '05/26/18': 1,
 '05/22/18': 2,
 't0tal': 1,
 '08:41:20': 1,
 '7:42:21': 1,
 "may22'18": 1,
 '01:39pm': 1,
 'tarrace': 1,
 '43017': 1,
 '5/16/2018': 1,
 'deschis': 1,
 'inchis'

In [52]:
sorted(data.vocabulary['words'].items(), key=lambda x: x[1]['count'], reverse=True)

[('total', {'count': 25, 'id': 13}),
 ('$', {'count': 17, 'id': 14}),
 ('date', {'count': 13, 'id': 12}),
 ('amount', {'count': 7, 'id': 24}),
 ('cambridge', {'count': 6, 'id': 4}),
 ('2018', {'count': 5, 'id': 126}),
 ('new', {'count': 5, 'id': 127}),
 ('york', {'count': 5, 'id': 128}),
 ('hyatt', {'count': 4, 'id': 2}),
 ('regency', {'count': 4, 'id': 3}),
 ('ny', {'count': 4, 'id': 20}),
 ('am', {'count': 4, 'id': 50}),
 ('may', {'count': 4, 'id': 55}),
 ('w', {'count': 4, 'id': 62}),
 ('blvd', {'count': 4, 'id': 70}),
 ('fl', {'count': 4, 'id': 90}),
 ('nc', {'count': 3, 'id': 6}),
 ('bellevue', {'count': 3, 'id': 9}),
 ('airport', {'count': 3, 'id': 47}),
 ('tampa', {'count': 3, 'id': 89}),
 ('pm', {'count': 3, 'id': 101}),
 ('10036', {'count': 3, 'id': 129}),
 ('ma', {'count': 3, 'id': 146}),
 ('due', {'count': 3, 'id': 147}),
 ('st', {'count': 3, 'id': 153}),
 ('charlotte', {'count': 2, 'id': 5}),
 ('square', {'count': 2, 'id': 10}),
 ('16.00', {'count': 2, 'id': 15}),
 ('the', 

In [38]:
trainer.opt['bow_ngram_range'] = (1, 3)
trainer.opt['bow_min_df'] = 3
mytrainer = trainer.BOWTrainer(data)
mytrainer.train()

2018-06-04 15:40:03.549210 Building vocabulary
2018-06-04 15:40:03.551204 Preparing data
2018-06-04 15:40:03.555194 Vectorizing
2018-06-04 15:40:03.562198 Traing
2018-06-04 15:40:03.564170 (0.7222222222222222, 0.6727272727272727)


In [39]:
mytrainer.eval()

2018-06-04 15:40:05.603153 Vectorizing
2018-06-04 15:40:05.606113 0.6727272727272727
[[18  0  0  0]
 [ 6  7  0  0]
 [11  0  0  0]
 [ 1  0  0 12]]


In [41]:
mytrainer = trainer.NNTrainer(data, num_classes=4)

2018-06-04 15:41:39.390019 Loading Glove
2018-06-04 15:41:40.907126 Building vocabulary
2018-06-04 15:41:40.909123 Preparing data
2018-06-04 15:41:40.911117 Buidling embeddings
2018-06-04 15:41:42.326332 Creating model


In [43]:
mytrainer.train(epochs=49000, epochs_eval=1000, verbose=False)

2018-06-04 15:42:19.222758 Training


C:\Users\mirce\git\ML\Experiments\TextClassification\models.py:246: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(X)


epoch 001000 loss 0.8888 train acc 0.9321 test acc 0.7455
epoch 002000 loss 0.8138 train acc 0.9568 test acc 0.7636
epoch 003000 loss 0.7874 train acc 0.9753 test acc 0.7818
epoch 004000 loss 0.7727 train acc 0.9877 test acc 0.7818
epoch 005000 loss 0.7667 train acc 0.9877 test acc 0.7818
epoch 006000 loss 0.7636 train acc 0.9877 test acc 0.7818
epoch 007000 loss 0.7618 train acc 0.9877 test acc 0.7818
epoch 008000 loss 0.7606 train acc 0.9877 test acc 0.7818
epoch 009000 loss 0.7598 train acc 0.9877 test acc 0.7818
epoch 010000 loss 0.7592 train acc 0.9877 test acc 0.7818
epoch 011000 loss 0.7587 train acc 0.9877 test acc 0.7818
epoch 012000 loss 0.7584 train acc 0.9877 test acc 0.7818
epoch 013000 loss 0.7581 train acc 0.9877 test acc 0.7818
epoch 014000 loss 0.7579 train acc 0.9877 test acc 0.7818
epoch 015000 loss 0.7577 train acc 0.9877 test acc 0.7818
epoch 016000 loss 0.7576 train acc 0.9877 test acc 0.7818
epoch 017000 loss 0.7574 train acc 0.9877 test acc 0.7818
epoch 018000 l

In [44]:
mytrainer.eval()

C:\Users\mirce\git\ML\Experiments\TextClassification\models.py:246: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(X)


2018-06-04 15:46:18.780983 0.7818181818181819
[[14  4  0  0]
 [ 0 13  0  0]
 [ 0  7  4  0]
 [ 0  1  0 12]]


In [15]:
len(mytrainer.vocabulary['words'])

1140

In [40]:
sorted(mytrainer.vocabulary['words'])

['$',
 "'s",
 '0',
 '0.00',
 '00',
 '0001',
 '00:13',
 '01:39pm',
 '02',
 '03',
 '04',
 '04/03/18',
 '04/03/2018',
 '04/04/18',
 '04/04/2018',
 '04/09/2018',
 '05',
 '05/12/18',
 '05/21/18',
 '05/22/18',
 '05/22/2018',
 '05/23/18',
 '05/26/18',
 '0608',
 '07:35',
 '07:56pm',
 '08',
 '08:01:00',
 '08:41:20',
 '09',
 '09:22pm',
 '1',
 '100',
 '10036',
 '108',
 '10:08am',
 '11:47',
 '12.25',
 '12:35',
 '12:38',
 '12:44',
 '12:48:21',
 '12:49pm',
 '12:55:42',
 '13.00',
 '1300',
 '13855',
 '13:04',
 '15:16',
 '15:30',
 '15:38',
 '16',
 '16.00',
 '17:14',
 '18',
 '18:20',
 '193.04',
 '1:39pm',
 '2',
 '2.55',
 '20.00',
 '20.12',
 '2018',
 '20:04',
 '2139',
 '22',
 '224.16',
 '2456',
 '25.66',
 '25.77',
 '270',
 '28203',
 '28277',
 '29403',
 '2:31',
 '3,0846.00014',
 '3-apr-2018',
 '3/27/1b',
 '30.19',
 '300',
 '3003',
 '301',
 '31',
 '311',
 '32nd',
 '33.80',
 '3339',
 '33612',
 '33617',
 '3418',
 '35.99',
 '36.04',
 '360',
 '3654',
 '391',
 '39th',
 '3:54pm',
 '4/02/18',
 '4/5/2018',
 '41.84